# Jekyll configuration

# Site settings
title: Colin Tinney
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Contact info
name: Colin Tinney
email: colintinney@gmail.com
displayedEmail: colintinney [at] gmail.com

# Social usernames
social:
  gitHub: 'cdtinney'
  linkedIn: 'cdtinney'
  spotify: cdtinney
  goodreads: 'cdtinney'

# Build settings
markdown: kramdown
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
