# Jekyll configuration

# Site settings
title: Colin Tinney
url: "https://colintinney.com"

# Contact info
name: Colin Tinney
email: colintinney@gmail.com
displayedEmail: colintinney [at] gmail.com

# Social usernames
social:
  gitHub: 'cdtinney'
  linkedIn: 'cdtinney'
  spotify: cdtinney
  goodreads: 'cdtinney'

# Build settings
markdown: kramdown
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
